# Generated by Django 5.1.1 on 2024-09-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('books', '0002_alter_book_id_delete_bookcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.emailaddress')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('tracking_code', models.PositiveBigIntegerField()),
                ('post_tracking_code', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=200)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.emailaddress')),
            ],
            options={
                'verbose_name_plural': 'Order Info',
            },
        ),
        migrations.CreateModel(
            name='OrderedProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderinfo')),
            ],
        ),
    ]
